### ISSUE TITLE
[Feature Request] Passing argv to nw.exe

### ISSUE THREAD

**Issue by fritx** [egoist/nwjs#10]
```js
// nwjs/nw
cli
  .command('*')
  .description('Run nwjs in a directory')
  .action(run)
```

https://github.com/nwjs/nw.js/wiki/App#synopsis

**Comment by egoist** [comment]
Done, `v1.4.0` supports this now. Simply do `nw . --argA xxx --argB xxx`.

**Comment by fritx** [comment]
Thanks! 6666

**Comment by fritx** [comment]
@egoist oops!
Seems v1.4.0 has a bug now!
Ctrl+C doesn't exit the NW process.

**Comment by fritx** [comment]
@egoist yup, I can reproduce the issue now.
In Windows 7 at my office.
WIth v1.3.1 it works fine, but with v1.4.0 `Ctrl+C` doesn't kill the nw process.

**Comment by egoist** [comment]
I will look into this, thanks.

**Comment by egoist** [comment]
temporarily use `child_process` to fix this 😂

**Comment by fritx** [comment]
Cool! Will try it later!
