### ISSUE TITLE
Feature Request: Automatically download NWjs without CLI commands

### ISSUE THREAD

**Issue by frankhale** [egoist/nwjs#12]
Since this project is inspired by Electron-Prebuilt it'd be fantastic if I could just depend on this in my project and spawn NWjs directly in my app to start it without specifying anything else. 

For instance, let's say my project depends on this: I run an `npm install` and `npm start` and my app spawns NWjs and my app starts up. Notice I did not have to specify any CLI commands to download a specific version of NWjs before I ran `npm start` and I didn't first install this into global.

This is the primary feature (I miss here) I use when I am using Electron-Prebuilt because it takes away any of the extra knowledge or user intervention to run your app in Electron. All dependencies are just ordinary npm modules and an `npm install` takes care of all the heavy lifting.

**Comment by egoist** [comment]
Yes, this is quit a neat feature of electron-prebuilt, intend to implement!

**Comment by fritx** [comment]
What about this? https://github.com/nwjs/npm-installer

```js
"scripts": {
  "start": "nw app"
},
"devDependencies": {
  "nw": "=0.12.3"
}
```

**Comment by fritx** [comment]
Or maybe using nwjs?

```js
"scripts": {
  "postinstall": "nw install 0.12.3 && nw use 0.12.3",
  "start": "nw app"
},
"devDependencies": {
  "nwjs": "*"
}
```

**Comment by frankhale** [comment]
This looks good! Thanks.
