### ISSUE TITLE
npm i -g nwjs failed at the posinstallscript Ubuntu 16.04

### ISSUE THREAD

**Issue by chpohl** [egoist/nwjs#15]
I tried installing nwjs via npm but the script fails. It is run on a Ubuntu 16.04 as su. I attached the npm-debug.log

[npm-debug.txt](https://github.com/egoist/nwjs/files/297903/npm-debug.txt)

**Comment by alejandro11k** [comment]
my solution:
first make directory manually
mkdir /home/user/.nwjs
and then
sudo npm i -g nwjs
xubuntu 16.04
