### ISSUE TITLE
Can't install latest (0.13.0-beta4)

### ISSUE THREAD

**Issue by PCMRStudio** [egoist/nwjs#6]
Replaces - with / in the download link

'/v0.13.0/beta4/nwjs-v0.13.0-beta4-win-x64.zip'

should be

path: '/v0.13.0-beta4/nwjs-v0.13.0-beta4-win-x64.zip'

**Comment by egoist** [comment]
thanks for reporting this, I'll fix it and refactor the code today. 😯

**Comment by egoist** [comment]
besides, you can try https://github.com/nwjs/npm-installer 😙

**Comment by egoist** [comment]
A new release 1.0.0 fixed this, and I changed the `nwjs` command to `nw`, updated the doc in [README](https://github.com/egoist/nwjs#usage) too 🔥
