### ISSUE TITLE
linux versions: 404 not found (distributed as tar.gz, not zip)

### ISSUE THREAD

**Issue by adriengibrat** [egoist/nwjs#8]
nw.js linux versions are only available as tar.gz archives, not zip
```nw install 0.13.0-beta5``` on linux yield a 404 error 
```
> nw install 0.13.0-beta5
Downloading 0.13.0-beta5.zip
Error: GET http://dl.nwjs.io/v0.13.0-beta5/nwjs-v0.13.0-beta5-linux-x64.zip returned 404
```

**Comment by egoist** [comment]
Sorry, I thought I fixed this but I forgot to. You are welcome to add a patch and send a pull request, or I will fix it later today myself. ✨

Thanks for reporting this issue.

**Comment by egoist** [comment]
Sorry for late fix, it should work in linux now. 🎉

**Comment by egoist** [comment]
I just tested it under ubuntu 14.04, run into some issue.

**Comment by adriengibrat** [comment]
Tanks, it works great.
Don't be sorry, it was a quick fix ;) 
And I could have send a PR!

**Comment by egoist** [comment]
@adriengibrat Glad to hear that, :beers:
